### ISSUE TITLE
Not all artifacts are being downloaded in vs-code

### ISSUE THREAD

**Issue by kdorking** [arnoudkooi/sn-scriptsync#101]
Some of the artifacts listed on the helper tab are not being downloaded to vs-code.

Attached is a screenshot of the helper page and a screenshot of vs-code folder

![Screenshot 2024-10-04 at 12 39 14 PM](https://github.com/user-attachments/assets/4bfe4c33-d48c-4cdb-a27b-ea367f69cbf7)

![Screenshot 2024-10-04 at 12 36 37 PM](https://github.com/user-attachments/assets/fe2781d7-d6b4-41cd-a07f-2d8475bcb9fd)

**Comment by arnoudkooi** [comment]
Not sure how to reproduce, can you share a scoped app that has this issue?

**Comment by kdorking** [comment]
Hi,

I am having the issue using the store app Network Inventory Core version 3.0.2


Regards,
Keith


From: arnoudkooi ***@***.***>
Date: Friday, October 4, 2024 at 5:20 PM
To: arnoudkooi/sn-scriptsync ***@***.***>
Cc: DORKING, KEITH ***@***.***>, Author ***@***.***>
Subject: Re: [arnoudkooi/sn-scriptsync] Not all artifacts are being downloaded in vs-code (Issue #101)
Not sure how to reproduce, can you share a scoped app that has this issue? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread. Message ID: <arnoudkooi/sn-scriptsync/issues/101/2394686267@ github. com>


Not sure how to reproduce, can you share a scoped app that has this issue?

**Comment by arnoudkooi** [comment]
Yes, I already pushed an update, but I forgot to mention in this issue. Can you check if it works as expected now?

**Comment by kdorking** [comment]
Yes, it is working as expected.  Thanks for the quick update.

**Comment by arnoudkooi** [comment]
Good!
