### ISSUE TITLE
Could not connect to websocket/Unable to get ScriptSync to connect to vscode

### ISSUE THREAD

**Issue by Karan-p-singh** [arnoudkooi/sn-scriptsync#102]
Issue: Unable to get ScriptSync to connect

ScriptSync installed in VSCode and running
-->![image](https://github.com/user-attachments/assets/0ce71bde-5341-42d5-8007-bcedd3e51ad9)
Folder path "ScriptSync"
-->![image](https://github.com/user-attachments/assets/d256d4dc-71e5-4253-bf5c-13069360a0e9)
When clicking on the ScriptSync from bowser I get the following page
-->![image](https://github.com/user-attachments/assets/ab1625a6-e334-46cd-b42d-2371bb5f2ba0)
Browser Terminal error
-->![image](https://github.com/user-attachments/assets/8b784cd4-0f21-4178-98ed-3ae496cd6d98)

Error when accessing http://localhost:1978/ from browser
"localhost sent an invalid response.
ERR_INVALID_HTTP_RESPONSE"

**Steps Tried**: 
1) Uninstalled the VS code extension, reran as admin and installed the extension again.
2) Checked excluded TCP port using "netsh interface ipv4 show excludedportrange protocol=tcp" Port 1978 is not excluded or reserved.

Thats where I am stuck at hoping to get some help

**Comment by arnoudkooi** [comment]
odd, did it used to work, or is this you're first install? 

What os and browser?
And do you see messages in the terminal output? 
![Code20241006 - 0741](https://github.com/user-attachments/assets/844bcc86-3c2f-4d59-a63b-f15e4ecc30da)

**Comment by Karan-p-singh** [comment]
Brilliant, you gave me a hint I was missing. On checking the output there was an error "[error] Error: listen EACCES: permission denied". 

Found a fix and now it's up and running 

Question: Is there a way for me to change which port locally the extension binds on if the port 1978 is already being used like in my case?

**"[error] Error: listen EACCES: permission denied"**

**Fix - Steps for anyone who faces a similar issue in future: **
Error on Output--> under extension host-- Error message - "[error] Error: listen EACCES: permission denied"
Step 1 Close Vscode

Step 2 Run "netstat -ano | findstr :1978" --> this gives you the service running on the port

Step 3: get the PID (it'll be the value in the red circle)
![image](https://github.com/user-attachments/assets/bc93b243-fea6-4ca7-bb3a-1ef52c47184d)

Step 4 Run "tasklist /FI "PID eq <PID>"  --> replace <PID> with the number in the red circle

Step 5: Run "taskkill /PID <PID> /F" to kill that service 

Relaunch vscode and it should connect

**Comment by arnoudkooi** [comment]
Thanks for the detailed analyses, glad it works!
