### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by meynt** [arnoudkooi/sn-scriptsync#14]
When installing to VS Code I receive the following error:

"Unable to install 'arnoudkooicom.sn-scriptsync'; there is no available version compatible with VS Code '1.24.1'.

**Comment by arnoudkooi** [comment]
Can you upgrade VS Code to the latest version?

**Comment by meynt** [comment]
That worked! I was attempting to update from within VS Code on MacOS and receiving a message that no updates were available. I went to their website and downloaded the installation files and was able to get it up to date.

Thank you again!

**Comment by arnoudkooi** [comment]
Great!
