### ISSUE TITLE
Syncing not working for Workflow Run Scripts 

### ISSUE THREAD

**Issue by odinsride** [arnoudkooi/sn-scriptsync#15]
Opening a Workflow Run Script via the Save Icon next to the script field opens the script successfully in VS Code, but upon saving my changes in VS Code, the script is not synced back to my instance. Helper tab shows that the script was opened but does not receive any further events when saving from VS Code. 

I'm running latest version of everything, and my SN Instance is on London Patch 8 Hotfix 2.

Thanks!

**Comment by arnoudkooi** [comment]
Thanks for flagging this. 

I checked it out and the script is actually in table sys_variable_value not on wf_activity 
This would get rather complex, but I'll try to find some time to dive in deeper and see if I can find a solution.  Thanks!

**Comment by arnoudkooi** [comment]
No solution found, this seems to complicated...
