### ISSUE TITLE
sn-scriptsync error when saving file

### ISSUE THREAD

**Issue by dgcst** [arnoudkooi/sn-scriptsync#16]
Recently I started to had an error on VSCode when saving a file with sn-scriptsync not running:

`Error while saving file: {}`

The file still saves, but this error always appears. Disabling the sn-scriptsync extension gets rid of the problem.

I am using VSCode on Mac, Version 1.35.1 (1.35.1).

**Comment by arnoudkooi** [comment]
Thanks for opening the issue. 
Could you try updating to 1.5.1 and let me know if that fixes it?

**Comment by dgcst** [comment]
It does solve it, yes. Thanks!

**Comment by arnoudkooi** [comment]
great!
