### ISSUE TITLE
saveRequestResponse throws exception when downloading a file

### ISSUE THREAD

**Issue by Blenderpics** [arnoudkooi/sn-scriptsync#19]
https://github.com/arnoudkooi/sn-scriptsync/blob/80e90b364214892b1be52ae2d100bb6905b627e5/src/extension.ts#L365  
This for-loop iterates over the key "results".  
"results" is not part of the responseJson.  
I've tested this by clicking the save button in a normal script field.  
responseJson contains a "result" key, but no "results" key.  
Also: "result" is of type object, not array.  
This seems to be no problem because the script is saved in `saveFieldAsFile` nevertheless.

**Comment by arnoudkooi** [comment]
I added a check haspropertie check, need to look in this further

**Comment by arnoudkooi** [comment]
Removed the call, should be resolved now
