### ISSUE TITLE
Error saving files

### ISSUE THREAD

**Issue by dtJon** [arnoudkooi/sn-scriptsync#2]
I have followed the example of your video and created a set of files for a widget.  The Scriptsync tab is up and shows [1].  I hit the purple icon in the widget editor and the files all get created.  However, if I try to save a file I get the following error.

The instance name is in the path twice.  Any idea what could be causing this?

 { "errno": -2, "code": "ENOENT", "syscall": "open", "path": "/Users/jonlind/Documents/sn-scriptsync/instancename/instancename/settings.json" }

Thanks again--I am so excited by this and can't wait to make it an integral part of my workflow.

**Comment by arnoudkooi** [comment]
Could you check if you have opened _/Documents/sn-scriptsync/_ in ServiceNow as folder? Maybe you opened _/Documents/sn-scriptsync/instancename/_ 
What is the OS you use?

Maybe we cans schedule something to go over.

**Comment by arnoudkooi** [comment]
Do you need help on this, or can I close it?

**Comment by dtJon** [comment]
I am so sorry--I figured it out.  I was in the wrong folder. I thought I
hadn't submitted this in the first place.  My apologies.  Please close it.

**Comment by arnoudkooi** [comment]
no, problem, glad it works.
