### ISSUE TITLE
Error while saving file: Required to provide Auth information

### ISSUE THREAD

**Issue by s2mill** [arnoudkooi/sn-scriptsync#20]
I am fairly recent to VS and made the decision to move away from Atom to be able to take full advantage of the SN Utils. I am very pleased with this decision in most cases.
However sometimes, when attempting to save from VS, I get the error "Required to provide Auth information" if the instance is set to log me out automatically after some time without activity. I'm not sure where I should be providing these since I then log myself back in, open a new helper tab that gives the message "Connected to VS Code ScriptScync WebSocket" but still am not able to save my open tab in VS.
I'm sure I must be missing something obvious.
Thank you

**Comment by arnoudkooi** [comment]
Thanks for calling this out. In this case the token expired, if you click on a save Icon in ServiceNow, it should work again. (doesn't have to be the save icon of the script your editing) Please try and let me know if it works. 
I will leave this open, to see if I can acquire a new token automatically.

**Comment by V1tamnT** [comment]
Have you had any luck with this? Using your workaround, I was able to reestablish my session, but it'd be awesome if the token could be acquired automatically.

Thanks for your work on this.

**Comment by arnoudkooi** [comment]
I'll try to have a look in the upcoming weeks.

**Comment by arnoudkooi** [comment]
Still working on this.
First improvement in SN Utils 3.4.7.0 is to type in the slashcommand `/token` This will push the current token to VS Code.

**Comment by arnoudkooi** [comment]
Does this solution help? I think a user interaction like this may be better, then auto acquiring from a security perspective.

**Comment by V1tamnT** [comment]
I know I'm going to sound like a total noob, but how do you do this in VS Code? I'm a recent adopter of it and don't know a lot about how a lot of the cool stuff works.

Sorry..

**Comment by V1tamnT** [comment]
Okay, this seems to work now. I'll continue to mess around with it, but so far I feel like this is a good solution.

Thanks!
