### ISSUE TITLE
Issues when using with Firefox Multi-Account Containers

### ISSUE THREAD

**Issue by odinsride** [arnoudkooi/sn-scriptsync#21]
Hi Arnoud, 

The new Firefox addon "Multi-Account Containers" allows users to assign websites to containers that run with their own set of cookies, etc.

When opening my ServiceNow instance in its own container, I am able to open scripts from the instance using sn-scriptsync, however saving gives the error message: "Required to provide Auth information"

I believe the issue is that the SN ScriptSync helper tab is opening in the default container, instead of the container the SN instance is opened in. I can re-open the SN ScriptSync Helper tab in the same container as my instance and everything works okay.

I don't know if you have control over which container the Helper tab opens in, but thought I would report it anyway in case anyone else runs into this issue.

Thanks!

**Comment by arnoudkooi** [comment]
I think you should be able to configure this in the "Multi-Account Containers" addon?  I'm afraid I cant control this.

**Comment by odinsride** [comment]
Thanks Arnoud, I figured as much, just wanted to check. Thanks!

**Comment by arnoudkooi** [comment]
Please check this, I looked in to it and made some progress...

https://github.com/arnoudkooi/ServiceNow-Utils/issues/40
