### ISSUE TITLE
Update Set picker in header not refreshing when you select "Make This My Current Set"

### ISSUE THREAD

**Issue by dgcst** [arnoudkooi/sn-scriptsync#22]
The changes to the Update Set and Application pickers are awesome, so thanks for that Arnoud!

However, I spot a small issue with the Update Set picker: if I open the record of an Update Set and click the UI Action "Make This My Current Set", the "display value" of the Update Set picker remains the same, not changing to the Update Set that is now current.

If I open the dropdown of the Update Set picker, the right one is selected, but not on the "display value".

As I said, this is a very minor issue, but something worth fixing if possible.

**Comment by arnoudkooi** [comment]
thanks but this is the wrong repo :) I'll check if i can solve this.

**Comment by dgcst** [comment]
Oh, sorry about that. Want me to move it to the right place?

**Comment by arnoudkooi** [comment]
Im removing this function for now. I did not find an easy way to refresh.
