### ISSUE TITLE
In Widget HTML Template, <script> tag doesn't sync properly

### ISSUE THREAD

**Issue by odinsride** [arnoudkooi/sn-scriptsync#24]
I have the following line in my HTML template:

```<script type="text/ng-template" id="myModal">```

When saving from VS Code, the attributes of the script tag are lost and the < and > characters sync to the instance with escape codes:

```&lt;script&gt;```

and 

```&lt;/script&gt;```

PS: I noticed this while working in my PDI which is on the New York release.

**Comment by arnoudkooi** [comment]
I'll have to look at this, but could this be something the instance does? Does it work when editing in the browser based widget editor?

**Comment by andfug** [comment]
I am experiencing the same issue with < and > becoming &lt; and &gt; for script-tags.

When editing directly in the web editor in my SN instance the script tags remains untouched and works as expected.

**Comment by arnoudkooi** [comment]
I've looked in to this, you would need to set system property 

`glide.rest.sanitize_request_input 
`
to false

**Comment by odinsride** [comment]
Great, thanks @arnoudkooi I will try this later today and let you know if it resolves my issue.

**Comment by odinsride** [comment]
Confirmed setting the property to false fixes the issue.  PR submitted for documentation purposes. Feel free to close this issue at your convenience Arnoud :smile:

**Comment by arnoudkooi** [comment]
Thanks, good idea to add a faq!
