### ISSUE TITLE
Change Widget File Names

### ISSUE THREAD

**Issue by CGraabaek** [arnoudkooi/sn-scriptsync#25]
I suggest changing the filenames for sp-widgets to the name of the widget + file ending. 
Example knowledge_blocks.html instead of 1 HTML Template. 

This would make it way easier to separate different widgets from each other in the Editor.

**Comment by arnoudkooi** [comment]
Did you consider setting this VS Code setting:
`"workbench.editor.labelFormat": "short"`

https://stackoverflow.com/a/50181247/562999

**Comment by CGraabaek** [comment]
Yeah it definitely helps, but I think it would still be a better alternative to have it in the actual file name - maybe just as a setting or something.
