### ISSUE TITLE
1.5.6 on marketplace broken

### ISSUE THREAD

**Issue by devendor** [arnoudkooi/sn-scriptsync#26]
I pieced together what seems to have happened and fixed it.  This might be something that doesn't effect case insensitive file systems.

The error I was getting was extension.snScriptSyncEnable not defined.

The 1.5.6 version from marketplace included a webpack dist/extension.js and both a ./out/ScopeTree.js and ./out/scopeTree.js.  The only major difference between published 1.5.6 and the git repo 1.5.5 is renaming ./out/scopeTree.js to ./out/ScopeTree.js which fixed an import compile error, and bumping the version. The git logs show the addition of webpack then the removal of webpack.

To fix it, all I did was:

```
cd ~/.vscode/extensions/arnoudkooicom.sn-scriptsync-1.5.6
npm i
rm out/* dist/*
./node_modules/.bin/tsc -p ./
cp out/* dist/*
```
It looks like simply removing artifacts and rebuilding is all it takes took to fix it for me.

**Comment by arnoudkooi** [comment]
Yes, I was trieng to add webpack, but facing issues with it, so removed it again. Does this issue require action?

**Comment by arnoudkooi** [comment]
Thanks closing this, as i dont believe theres a call to action
