### ISSUE TITLE
ScriptSync does not  work with PowerShell Custom Activities

### ISSUE THREAD

**Issue by bdbartlett** [arnoudkooi/sn-scriptsync#27]
Currently writing workflows that contain PowerShell custom activities. The PowerShell custom activity template contains Pre and Post Processing JavaScript sections that do indeed have the ScriptSync icon next to them. However the PowerShell Command window where I enter my PS Code does not have that icon. most of what I do is in PowerShell scripts aimed at Windows platform integration point and Virtual Servers. Am I missing a setup option or is PowerShell not currently supported by ScriptSync with VS Code?

**Comment by arnoudkooi** [comment]
what is the table and fieldname for this?

**Comment by bdbartlett** [comment]
Dictionary Info: wf_element_activity.input_transform.ds__909d4ee0.command

Table	wf_element_activity
Field	input_transform
Type	data_object
Max Length	65000
Attributes	accept_code=activityInput,​list_layout_ignore=true,​slushbucket_ref_no_expand=true,​structure_key=base_provider.name

**Comment by bdbartlett** [comment]
Command | input_transform.ds__909d4ee0.command

**Comment by arnoudkooi** [comment]
This is probably the same issue: https://github.com/arnoudkooi/sn-scriptsync/issues/15
I dont think there is an easy way to determine the database field at runtime. Will have a look, or maybe you can :)

**Comment by bdbartlett** [comment]
I am not convinced this is the same issue as #15.  I am not creating a Workflow PowerShell Run Script in the workflow. I am creating a custom activity from the Custom Tab, Plus sign, and selecting PowerShell template. At this point it is not yet associated with a workflow. The ScriptSync  icon exists in the blank PowerShell Custom  Activity template for Pre and Post Processing JS code, but not for the PowerShell command field in the "Execution Command" tab of the Custom Activity. Screen shots attached.

Thanks in advance for any help.

![FieldInfo](https://user-images.githubusercontent.com/47126988/65257923-08f77a80-dad0-11e9-9dc8-1840b36632c9.PNG)
![PSExecution](https://user-images.githubusercontent.com/47126988/65257924-09901100-dad0-11e9-8dc9-80f6ccf3b7e9.PNG)
![Pre-Process](https://user-images.githubusercontent.com/47126988/65257925-09901100-dad0-11e9-8325-da50ffcade8c.PNG)

**Comment by arnoudkooi** [comment]
No solution found, this seems to complicated...
