### ISSUE TITLE
Service Portal Theme CSS files open with .js extension

### ISSUE THREAD

**Issue by odinsride** [arnoudkooi/sn-scriptsync#29]
Not a breaking feature, but when I open a Service Portal theme CSS via clicking on the open in VS Code icon from ServiceNow, it opens the CSS file with an extension of .js ... I would expect it to open as .css or .scss so that VS Code applies the appropriate file type/syntax highlighting.

**Comment by arnoudkooi** [comment]
Thanks for addressing!
Could you try upgrading 1.5.8 to see if it is fixed?

**Comment by odinsride** [comment]
Works perfectly now! Thanks for the quick fix :)
