### ISSUE TITLE
Hi, will there be support not on Servicenow domain?﻿

### ISSUE THREAD

**Issue by Greifrut** [arnoudkooi/sn-scriptsync#3]
Hi, will there be support not on Servicenow domain. Different from *.service-now.com ?

**Comment by arnoudkooi** [comment]
Please try the onprem version of the extension https://chrome.google.com/webstore/detail/lfabkiipmidkmhplochgpbaeekjjfbch/
Be sure to wait until version 3.1 is available. Let me know if it works.

**Comment by Greifrut** [comment]
Thanks, everything works fine
