### ISSUE TITLE
Possibility to resync after some time?

### ISSUE THREAD

**Issue by DkVagabonden** [arnoudkooi/sn-scriptsync#31]
Hello, 

Would it be possible to make it, so that we have the possibility to resync the script in Visual studio code? Lets say after a day i need to work on the same script i worked on yesterday? But my 
colleague made some changes to the script? Instead of finding it again in servicenow and clicking on the "save icon" i can just open up VSC and "refresh" the script?

**Comment by arnoudkooi** [comment]
I'll have a look, may take some time..
(the behaviour of studio integration should already work like this, when you open a file from that tab, it will always pull the current version before opening, if the file is not opened already)
