### ISSUE TITLE
<script> in HTML Template

### ISSUE THREAD

**Issue by daszod** [arnoudkooi/sn-scriptsync#32]
Hi, 
i have embedded a <script> before the first <div> in the HTML Template.
And everytime i am saving the document and the sync upload my document to Servicenow it gives me some other code. 

example in VSC: 
```javascript
<script type="text/ng-template" id="dummy.xml">
    <div ng-include="'dummy'"></div>
</script>
<div class=""> ... the usual html code follows.
```
What Snow shows me after the sync:
```javascript
&lt;script&gt;
    <div ng-include="dummy'"></div>
&lt;/script&gt;
<div class=""> ... the usual html code follows.
```
When i use the Servicenow Widget Editor there is no problem and the code works.

**Comment by arnoudkooi** [comment]
This is a copy of 
https://github.com/arnoudkooi/sn-scriptsync/issues/24 
Update documentation:
https://github.com/arnoudkooi/sn-scriptsync/pull/28
So the solution is you would need to set system property in your instance 
`glide.rest.sanitize_request_input
`to false
