### ISSUE TITLE
Force start ScriptSync service?

### ISSUE THREAD

**Issue by likehoy** [arnoudkooi/sn-scriptsync#33]
I am using Firefox and Code on linux, with sn-scriptsync installed.

VS Script Sync is enabled on browser.
The ScriptSync service is not showing the Statusbar for me to manually start the service.
I've also set the default folder to attempt to automatically start the service.

In both cases, the helper tab is reporting;
"Could not connect to WebSocket.
Check if VS Code is running and wait for connection or reload the page."

It's possible that the extension is not at at fault, but for me to confirm, is there another way to force start the service other than the through the statusbar/open folder?

**Comment by arnoudkooi** [comment]
It has a command: `ServiceNow ScriptSync Enable`

You can check if the websocket server  is running by typing in browser: http://localhost:1978 
It should give a message `Upgrade Required`

**Comment by likehoy** [comment]
Tried ` ServiceNow ScriptSync Enable`
"command 'extension.snScriptSyncEnable' not found."

**Comment by arnoudkooi** [comment]
Maybe try removing it from VS Code and reinstall

**Comment by likehoy** [comment]
Removed and reinstalled to no avail.

**Comment by arnoudkooi** [comment]
Are your node and stuff up to date, do you have some more info to share, to be able to debug? 
Also Check logs in VS Code

**Comment by likehoy** [comment]
node 12.13.0-1
code 1.39.2-1
'arnoudkooicom.sn-scriptsync.sn-scripts' 1.5.8
![2019-11-09](https://user-images.githubusercontent.com/57573057/68536076-d128e880-0344-11ea-8992-ee142724077d.png)

**Comment by arnoudkooi** [comment]
Can you try updating to 1.5.9? I changed the reference to the ScopeTree.ts file

**Comment by arnoudkooi** [comment]
Disregard, my last and try getting and testing 1.6.0 :)

**Comment by likehoy** [comment]
1.6.0 is working.
Service toggle showing in status bar.
and Auto start working.
Thank you

**Comment by arnoudkooi** [comment]
Cool, thanks for creating the issue!
