### ISSUE TITLE
Adding features of the official ServiceNow VS Code addon

### ISSUE THREAD

**Issue by Blenderpics** [arnoudkooi/sn-scriptsync#34]
Hey!

As you probably already know, ServiceNow released it's own VS Code addon. (https://developer.servicenow.com/blog.do?p=/post/vscode/)  
Although i can't use it since it does not support SAML authentication (OAuth and Basic Auth is not possible in my usecase), i have to say that some features are pretty nice.  
  
The "Merge conflict" detection is pretty huge for dev teams with more than 3 developers.  
Also the possibility to run arbitrary source code by selecting it and clicking "run as background script" is pretty nice for debugging.  
  
I would like to see those features implemented in sn-scriptsync as well.  
Are there any plans on doing so?  
If so: how can we help?

**Comment by Blenderpics** [comment]
May be related to https://github.com/arnoudkooi/sn-scriptsync/issues/31, since the ServiceNow VS Code addon does support refreshing all files as well.

**Comment by arnoudkooi** [comment]
If you have some cycles, Im ok if you add some of these features. I do have some commented code to resync, but not finished.

**Comment by Blenderpics** [comment]
I might find some time in January. I guess i could give it a shot.

**Comment by arnoudkooi** [comment]
closing this for now
