### ISSUE TITLE
Adding script from asmt_metric leaves a script without extension.

### ISSUE THREAD

**Issue by CGraabaek** [arnoudkooi/sn-scriptsync#37]
When adding a script from the table _asmt_metric_ there is no extension on the file.

**Comment by arnoudkooi** [comment]
I can not reproduce.
Do you have a dot in the name of the record?

**Comment by CGraabaek** [comment]
You are right, I don't have a dot. in the name, but it does end with a '?'. 

So a name could be: 
_How many KB articles has been published based on knowledge candidates over the last 3 months?_

I guess you could argue that it's bad naming on my part and i should just leave the question mark out of the name.

**Comment by arnoudkooi** [comment]
Ok, Ill check if I can remove all alphanumeric chars, except for some midserver type files I'm trying to respect the file-extension

**Comment by arnoudkooi** [comment]
This should be fixed in 1.6.3 Please try and close if fixed
