### ISSUE TITLE
Script sync not working on macOS

### ISSUE THREAD

**Issue by Sauron-Dev** [arnoudkooi/sn-scriptsync#39]
Hi there, 
since today the script sync with the chrome on premise plugin and vs code does not work anymore on my macOS. With windows it still works. Could this be related to the chrome plugin update yesterday?

Thanks for your help.

**Comment by arnoudkooi** [comment]
For me it works, did you try restarting, if it persist could you share more details what does and doesnt work?

**Comment by Sauron-Dev** [comment]
Hi there, wow thanks for the fast response, I really appreciate that. I must say how much I love your plugin and it really helps.

So what information could I give you?

- I am using the onPrem version of the chrome plugin
- Everything is working on the chrome plugin except the vs code sync
- chrome plugin, helper tab says "connected", so I assume on vs code side everything is setup right
- When I click on the scriptsync symbol beside a script include field, the symbol gets green and I get no error message, but also no additional log entry on the helper tab
- 09.03.2020 21:00 GMT it worked everything
- Today starting work, 10.03.2020 08:00 GMT, above behaviour occured
- My colleague with a MacBook has exactly the same problem, my colleague with a windows machine has no problems 

What did I do?
- Restarted the MacBook
- Removed the chrome plugin and reinstalled (I activate the vs sync in the helper config after reinstalling)



Can I provide more information that helps?


Thank you very much.

**Comment by arnoudkooi** [comment]
Please update to version 1.6.6
I recommend restarting Chrome and VS Code after the update and try again.

If it works I would appreciate a review of the Chrome and VS Code extension :)

**Comment by andrewhussar** [comment]
I can confirm, now it's working again!  💯 
Thank you for the quick action and all of your work!

**Comment by Sauron-Dev** [comment]
You are the man! It works again, thank you so much :) *Goes searching the donate button*

**Comment by arnoudkooi** [comment]
Great, thanks for addressing the issue!

**Comment by arnoudkooi** [comment]
Please update to version 1.7.0 of sn-scriptsync.
I had some more issues reported. It should now work as expected (again)
