### ISSUE TITLE
Missing reload functionality

### ISSUE THREAD

**Issue by Blenderpics** [arnoudkooi/sn-scriptsync#4]
Since we work in a project with multiple developers, a reload functionality in the vs code addon would be nice, since the only way to reload your files seems to be to delete and re-fetch them

**Comment by arnoudkooi** [comment]
Thanks, Ill think of a way to integrate this. Suggestions?

**Comment by Blenderpics** [comment]
I think the user friendliest way of accomplishing this would be to add a context menu item in vs studio.
 
my current understanding is that the addon simply attaches to the save-file event of vs studio.
so perhaps a context menu integration would be out of scope for this project? since i usually don't work with vs code, nor do i code vs code extensions, i can't estimate the effort a context menu integration would need.

a simpler way which would be compatible with the current architecture of the addon, would be a marker file. 
as soon as a marker file gets placed in the root scope of the vs code project, all items get reloaded.
this would be a quite dirty solution to the problem but i guess it would be very simple implementation wise.

let me know if i can be of any help with this issue

**Comment by arnoudkooi** [comment]
The idea of the extension is to keep ServiceNow as the source of true, so I'm not planning to implement this. If you feel like chiming in, please feel free.
