### ISSUE TITLE
Unable to start service on Fedora 31 VSCode

### ISSUE THREAD

**Issue by shutupandshave** [arnoudkooi/sn-scriptsync#40]
Node -v12.16.1
Code: 1.42.1

![image](https://user-images.githubusercontent.com/918561/77766300-60eedb00-7037-11ea-8851-616693bafeaa.png)

**Comment by shutupandshave** [comment]
![image](https://user-images.githubusercontent.com/918561/77766368-7532d800-7037-11ea-9efe-46e6591e50b0.png)

**Comment by shutupandshave** [comment]
![image](https://user-images.githubusercontent.com/918561/77766438-8f6cb600-7037-11ea-94cd-50adfa6e3cbd.png)

**Comment by shutupandshave** [comment]
abstractExtensionService.ts:396 Activating extension 'arnoudkooicom.sn-scriptsync' failed: A system error occurred: uv_os_get_passwd returned ENOENT (no such file or directory).

**Comment by shutupandshave** [comment]
Updating Node and VSCode fixed it

**Comment by arnoudkooi** [comment]
Thank you, glad it's resolved!
