### ISSUE TITLE
Slash Commands Not Working in Some Cases in Edge Chromium

### ISSUE THREAD

**Issue by V1tamnT** [arnoudkooi/sn-scriptsync#41]
I know Edge Chromium is relatively new and it's probably not officially supported here but, just in case.

If I enter /incident and hit the space bar to add -f or other filters, the slash command prompt immediately switches to /nav incident. Based on the gif you posted with the newest update, I would have expected it to allow me to filter incidents with a slash command. 

I can't record the process, but I added an image of the command after I hit space

![image](https://user-images.githubusercontent.com/20115051/80806191-f70ea780-8b87-11ea-92f8-88f8484d8266.png)

Hoping you can help here.

Thanks for all your work on this. It's huge for me.

Jim

**Comment by arnoudkooi** [comment]
Have you checked the following tweets, I think your missing the rightarrow:

https://twitter.com/sn_utils/status/1248304008864976906
https://twitter.com/sn_utils/status/1249735135236251648

**Comment by V1tamnT** [comment]
Thanks for the rapid response. You are correct...I was not using the right arrow. It does appear to be working.

Again Arnoud, I appreciate your dedication and work on sn-scriptsync. This is actually opening up a way for us to implement version control without converting all of our global apps to scoped.

Jim

**Comment by arnoudkooi** [comment]
Great! (This point was actualy related to SN Utils, not scriptsync..)
