### ISSUE TITLE
Can't stop synching from statusbutton

### ISSUE THREAD

**Issue by alonsotorres** [arnoudkooi/sn-scriptsync#42]
When clicking the "SN ScriptSync:Running" button at the status bar in VS Code, it does not stop.
If a try to save a file that has lost connections to the browser I get the following error:

No WebSocket connection. Please open SN ScriptSync in a browser

![VS Code synch error](https://user-images.githubusercontent.com/643244/83960935-01415700-a854-11ea-8fdf-69f4da623e6b.png)

**Comment by arnoudkooi** [comment]
Thanks, this should be fixed in the latest commit. Problem is I can't publish right now due to a issue with my account. I'll update when available

**Comment by arnoudkooi** [comment]
Can you update to 1.8 and try?

**Comment by alonsotorres** [comment]
It is working now!!
Thank you!!!!
