### ISSUE TITLE
[Feature request] Script from Flow Action Script Step

### ISSUE THREAD

**Issue by CGraabaek** [arnoudkooi/sn-scriptsync#43]
Hi, 

Scripts from the Flow Designer - Action Script Step cannot be synced.
This would be a nice addition.

**Comment by physi** [comment]
That would be a very nice enhancement, indeed!

**Comment by arnoudkooi** [comment]
Can you try version 6.0.4.3? 
On top of the page of an action there now is a [scriptsync button](https://twitter.com/sn_utils/status/1528586520700981249)
