### ISSUE TITLE
Support for vanity URLs

### ISSUE THREAD

**Issue by NickWright** [arnoudkooi/sn-scriptsync#45]
Not sure how feasible it would be but would be great to be able to use the plugin with instances that have vanity urls.

**Comment by arnoudkooi** [comment]
Not sure what you mean, can you share an example?

**Comment by arnoudkooi** [comment]
I supose you mean non service-now.com urls? SN ScriptSyync supports this, you only need the OnPrem version of SN Utils, direct link to all versions on my site: https://www.arnoudkooi.com/ 

Please take note of this tweet:
https://twitter.com/sn_utils/status/1248870425549049857
(and all others if you have some time ;) )

**Comment by NickWright** [comment]
Oh awesome thats what I was looking for, thank you!
