### ISSUE TITLE
VS Extension could not be installed (not compatible version with VS 1.24.1)

### ISSUE THREAD

**Issue by Trampf** [arnoudkooi/sn-scriptsync#46]
Hello, 
thank you for this awesome extension. 

I tried to install the VS extension and got the error message, that it cant be installed since there is no version compatible with VS 1.24.1.

Is there a fix to this?

Cheers,
Trampf

**Comment by arnoudkooi** [comment]
Can you upgrade VS code?

**Comment by arnoudkooi** [comment]
Just checked, seems your running the may 2018 version, I recommend you update and let me know.

**Comment by Trampf** [comment]
Well, obviously that was correct. For some reason I thought my company had a recent update! Thank you!
