### ISSUE TITLE
Widget: Templates should also be sync'able

### ISSUE THREAD

**Issue by Blenderpics** [arnoudkooi/sn-scriptsync#5]
Hey!

I usually organize big widgets with templates to reduce the visual complexity.
However templates don't get synchronised when hitting the "download-button" in the widget editor.
(same goes for widget dependencies but since they are not part of the widget itself (at least in my opinion) im ok with this)
Therefore i can't use sn-scriptsync for widgets where i use templates.

if i find some time i will implement it my self and create a pull request!

**Comment by arnoudkooi** [comment]
I just commmited a update to support this, will publish it in the next couple of days.

**Comment by Blenderpics** [comment]
Sounds great!
Thanks for your work!
The VS-Code integration really makes developing with servicenow much more bearable

**Comment by arnoudkooi** [comment]
Please update and try both  this and the browser extension and check if it works.

**Comment by Blenderpics** [comment]
Works beautifully! Thanks!
