### ISSUE TITLE
'arnoudkooicom.sn-scriptsync' failed: Cannot read property 'endsWith' of undefined.

### ISSUE THREAD

**Issue by J2-Tech** [arnoudkooi/sn-scriptsync#51]
I just updated VSCode and now sn-scriptsync will not activate, i am getting this in the developper console : 

`Activating extension 'arnoudkooicom.sn-scriptsync' failed: Cannot read property 'endsWith' of undefined.`

So whenever i click to start sn-scriptsync i get this error 

`Command 'sn-scriptsync: Enable' resulted in an error (command 'extension.snScriptSyncEnable' not found)`

VSCode 1.55.0
sn-scriptsync 1.9.7

**Comment by arnoudkooi** [comment]
Im not able to replicate, could you try to reinstall the extension?

**Comment by J2-Tech** [comment]
I have reinstalled the extension, as well as the two previous versions of VSCode and it is still happenning.
![image](https://user-images.githubusercontent.com/14958070/114047358-a3a4df00-9857-11eb-8bd2-f653bf1d0b3d.png)
![image](https://user-images.githubusercontent.com/14958070/114047431-adc6dd80-9857-11eb-81ab-cc6d37eda5d3.png)

**Comment by arnoudkooi** [comment]
Did you open a folder before starting scriptsync?

**Comment by arnoudkooi** [comment]
Or join my zoom room to troubleshout https://servicenow.zoom.us/my/arnoudkooi

**Comment by J2-Tech** [comment]
I just had to open a folder, you were correct, this resolved my issue ! 

Thank you, have a nice day !

**Comment by arnoudkooi** [comment]
Good, Ill add some errorhandling...
