### ISSUE TITLE
Getting error when saving workflow from Visual Code

### ISSUE THREAD

**Issue by hampusfredriksson** [arnoudkooi/sn-scriptsync#52]
I'm having same issue found in #15 

I see the helper tab is up and running and I can press the little sync script icon from workflow advanced tab which sends the code correctly to vs code. Then when I'm saving in vs code I'm getting a notification with this error message:
![image](https://user-images.githubusercontent.com/42962227/117831805-3aa8f080-b275-11eb-8fd0-4d31621bb561.png)

Running latest ServiceNow patch and up-to-date with sn synscript from marketplace also. 

Let me know if/how I can provide more information or logs.

**Comment by arnoudkooi** [comment]
This is also about Workflow Script? maybe as a workaround you could open it from sys_variable_value table and sync from there...

**Comment by arnoudkooi** [comment]
Can you check in the latest version (2.1.0 and SN Utils 5.2.9.0) if it works I made a function that us a BG script. Please check and let me know.
Note that you need to refresh browser to see the changes.

**Comment by V1tamnT** [comment]
Admittedly, I haven't followed all the development changes as closely as I could (a testament to how well this works), but the last I heard, you could not save a script in a workflow. I've never been able to do it and I think I remember seeing multiple discussions where the developer said it would be hard to save this due to the way workflows work.

I'd LOVE to be wrong about this though.

**Comment by arnoudkooi** [comment]
This was added in todays update @V1tamnT 
Please check if it works if you can.

**Comment by V1tamnT** [comment]
I've verified my VS Code ScriptSync extension is v2.1.0 and SNUtils is 5.2.9. The good news is that I no longer get an error when ScriptSync is running and saving to a Run Script activity. However, I am not seeing a change actually being saved to that activity.

I can see in the Helper tab that something is being saved, but it's not really saving. I've refreshed the browser, but I still do not see the change reflected in the activity.

**Comment by arnoudkooi** [comment]
Thanks for checking. Is it global scope and do you see something in log? Or click the link in helper tab..

**Comment by V1tamnT** [comment]
Yes, this is global. I didn't look in a ServiceNow log (not sure which one to look at), but there is an entry in the Helper tab saying it saved to ServiceNow. I'd send a screen capture, but I have to be careful not to send too much info related to my company's instances.

**Comment by arnoudkooi** [comment]
I just published a [minor update](https://github.com/arnoudkooi/ServiceNow-Utils/commit/f5a59ac5635acd0a45a681c0b9ebac2ae69b6986) to SN Utils 5.2.9.1., that is now available. Could you update and check ?

**Comment by V1tamnT** [comment]
That appears to have done the trick. I can see an entry in the Helper tab where a background script was executed. After closing the activity and reopening it, I see the update.

It worth noting that, as with other scripts, you can save the activity with the Run Script activity modal closed, once you have it loaded in VS Code.

This. Is. Awesome!

**Comment by arnoudkooi** [comment]
Great, and note while you do have it open, you can quickly refresh with a double-click in an empty space of the header bar
![image](https://user-images.githubusercontent.com/840781/145897911-e2fce980-b0b4-470d-a410-3f038cd92e9a.png)

**Comment by bjamn** [comment]
WOW!!! This is fantastic. Great work! I am amazed that this functionality is free!! Thank you so much.
