### ISSUE TITLE
Regex not populated correctly for background script

### ISSUE THREAD

**Issue by gczutor** [arnoudkooi/sn-scriptsync#53]
Using this line in my code in VSCode:
`short_description == short_description.match(/^\[.+\s\|\s.+\]\s.+/);`

And what's populated in the background script editor in SN is:
`short_description == short_description.match(/^[.+s|s.+]s.+/);`
(note the missing backslashes in the regex)

Steps to reproduce:
- open Scripts - Background in SN navigator
- click to mirror editor in sn-scriptsync
- write/paste the above regex in VSCode
- see that backslashes have been removed in the SN editor

**Comment by arnoudkooi** [comment]
I was wondering if anyone uses this :)
I can replicate, this needs to be addressed in SN Utils. I'll have a look

**Comment by gczutor** [comment]
Now you know there's at least one; me. :)

Actually, I've found that escaping the backslash (like \\) works but then the resulting code is not just a copy-paste away from any other script field (like Script Include) so it's not very comfortable. You may want to have a look escaping it 'yourself' when sending it from VSCode to the browser, I think that's the place to catch it.

**Comment by arnoudkooi** [comment]
I did do an update here, could you update to 1.9.9 and try? Just curious are you also using it for other purposes?

**Comment by arnoudkooi** [comment]
I do need to make an update to SN Utils as well, please stand by :)

**Comment by arnoudkooi** [comment]
Please update SN Utils to 5.0.2 and try

**Comment by arnoudkooi** [comment]
were you able to try?

**Comment by gczutor** [comment]
Sorry mate not yet. Going to get back to you as soon as I can.

**Comment by gczutor** [comment]
Seems working fine with 1.9.9

Well for what purpose I use sn-scriptsync? I usually 'mirror' code of SIs and other records into it and develop my code. Works great (now also with regular expressions :)) and the comparisn window is great if anything happens. I used to use S.N.I.C.H but started not liking its folder structure and that I have to add sys_id for each table config to get the script files named accordingly in order to differentiate between same named records. You have this as default in sn-scriptsync so it's better for me.

**Comment by arnoudkooi** [comment]
Great, thanks for feedback and confirming it works!
