### ISSUE TITLE
ATF Step Sync is only working one way

### ISSUE THREAD

**Issue by make-servicenow-great-again** [arnoudkooi/sn-scriptsync#59]
sn-scriptsync does not work properly with script fields from sys_atf_step table.
It is only possible to sync the script files from servicenow to vs code but not the otther way round.

Saving in VS Code only results in a generic error message: error while saving file {}

**Comment by arnoudkooi** [comment]
The problem here is the same as in #52 
Unless someone knows a API that has write access to `sys_variable_value` I don't see a workaround :(

**Comment by arnoudkooi** [comment]
Can you check in the latest version (2.1.0 and SN Utils 5.2.9.0) if it works I made a function that us a BG script. Please check and let me know.
Note that you need to refresh browser to see the changes.
