### ISSUE TITLE
Can't "Mirror in sn-scriptsync" to VS Code

### ISSUE THREAD

**Issue by davewburns** [arnoudkooi/sn-scriptsync#60]
This function appears broken.  Tried both Chrome and Firefox.  When viewing the console, the following errors are present, not sure if it is related:
![image](https://user-images.githubusercontent.com/2111775/147245848-ce24b13d-f7d4-435e-b202-4a47194a03e2.png)

**Comment by arnoudkooi** [comment]
Thanks, I was considering removing this feature giving you now have the script editor on background scripts. Do you have a reason to prefer this Mirror function?

**Comment by davewburns** [comment]
I just prefer working in VS Code as it helps me to keep my different projects organized.

**Comment by arnoudkooi** [comment]
This should be fixed in SN Utils 5.2.9.5, please check (FireFox available, Chrome Pending approval)

**Comment by davewburns** [comment]
Yes, it's working again now.  Thank you.
