### ISSUE TITLE
Cannot open the workflow

### ISSUE THREAD

**Issue by vtuong220889** [arnoudkooi/sn-scriptsync#61]
Open any workflow in Workflow Editor. It did not display as expectation

**Comment by arnoudkooi** [comment]
What is exactly the issue?
Please add more context like steps to reproduce and screenshots.

**Comment by vtuong220889** [comment]
Step to reproduce:
- Go to Workflow: Workflow --> Workflow Editor
- Click on that, it will pop up to Workflow IDE
- It displays the blank
- 
![workflow_issue](https://user-images.githubusercontent.com/14172984/148327661-f0d0b9fa-a633-431f-a8f6-46db96d54e0b.PNG)


Notes: I am using a commercial instance, then I would like to blind the url. I tried to use personal instance, and it works well.

**Comment by arnoudkooi** [comment]
Can you disable SN Utils and reload?
If it still occurs then it is not a SN Utils issue, if so please open developer tools and check browser errors.
Either way this is not a sn-scriptsync issue, as sn-scriptsync is the VS Code extension.

**Comment by vtuong220889** [comment]
You're right! It seems to be an issue in only that instance. And even I disabled the SN Utils extension and reloaded. Sorry for my mistaken reported.
