### ISSUE TITLE
Request: Refresh SN Script in Visual Studio Code

### ISSUE THREAD

**Issue by Trampf** [arnoudkooi/sn-scriptsync#62]
Hey Arnouud,

would it be possible to have a button to refresh the script in VS Code to get the current version from ServiceNow?

Sometimes I have the issue, that the Versions I have in ServiceNow are not the same as the VS Code. Then I always have to go the script and reload it again.

It would be very comfortable to refresh the script from inside VS Code.

**Comment by arnoudkooi** [comment]
The idea is to keep the instance leading (source of truth) and use VS Code as a companion. 
Having that said, I'll have a look  :)

**Comment by NeuraalLabs** [comment]
+1 I came here looking for this exact feature. SN would still be the source of truth, would be great if we can execute a command to refresh all the items open in SN with the code in SN

**Comment by arnoudkooi** [comment]
Please upgrade and check. see [this tweet
](https://twitter.com/sn_utils/status/1495141658861703170) 
Besides the refresh **Open in Instance** command is added

Assigned shortcuts
```
            {
                "command": "extension.openInInstance",
                "key": "ctrl+alt+i",
                "mac": "ctrl+cmd+i"
            },
            {
                "command": "extension.refreshFromInstance",
                "key": "ctrl+alt+r",
                "mac": "ctrl+cmd+r"
            }
```

**Comment by NeuraalLabs** [comment]
@arnoudkooi AWESOME! This is great. Thank you! 

Not to look a gift horse in the mouth, but do you see any possibility for being able to do it for everything open in a workspace with a single command?

**Comment by Trampf** [comment]
@arnoudkooi Super cool! Thanks for implementing it! 

NeuraalLabs suggestion is also great to refresh the whole set, but I am super happy with your new update. Works like a charm!
