### ISSUE TITLE
Request: Add support for GlideQuery() in scriptsync / background scripts

### ISSUE THREAD

**Issue by davewburns** [arnoudkooi/sn-scriptsync#63]
When I type GlideQuery into a script, I always get the autocomplete going to GlideQueryCondition, I have manually edited the server.ts file to add: 
`class GlideQuery {
    constructor(tableName: string) { };
}`
to allow me to use this.  It's not perfect as it leaves out most of the actual functions of GlideQuery, but it does allow me to use it as an autocomplete entry.

**Comment by arnoudkooi** [comment]
Sorry for the late reply. Would you have a more complete version that covers the functions? I can't find it..

**Comment by davewburns** [comment]
I know it actually lives in the script includes. I can dig it up.

**Comment by arnoudkooi** [comment]
I checked and just added the GlideQuery scriptinclude to the autocomplete folder works.
Just published version version 2.2.0

**Comment by arnoudkooi** [comment]
Please try if it works, closing for now (Issue Cleanup night ;) )
