### ISSUE TITLE
Add custom Intellisense

### ISSUE THREAD

**Issue by Zmud1** [arnoudkooi/sn-scriptsync#64]
Hi,
Is there a way to add custom code snippets to appear in the VSCode-like background editor? Iam talking about the functionality of Syntax Macros. Like, for example, I would like to be able to input:

"vargr" +Tab/Enter  in the background script window 

And have it automatically changed into : 

var gr = new GlideRecord("");
gr.addQuery("name", "value");
gr.query();
while(gr.next()) {
}

Is there an extension file I can modify for that functionality to work? I mean, the original Intelllisense must be somewhere defined, right?

**Comment by Zmud1** [comment]
Sure, but what I mean is for this functionality to work in a Background Script that is enchanced by SNUtils. Please, see below. While VSCode uses 'gliderecord' snippet and inserts code, the Background Script in browser doesn't see "gliderecord" snippet.
Is there a way to change that?
<img width="798" alt="image" src="https://user-images.githubusercontent.com/43832632/152411083-a3cf0bdd-d021-4d29-a0b0-a762da6a0865.png">

**Comment by arnoudkooi** [comment]
Ah ok, this is about SN Utils, not vs-scriptsync. For now you could try the Mirro in sn-scriptsync or an external snippet manager...

**Comment by arnoudkooi** [comment]
This is about SN Utils
