### ISSUE TITLE
Error, please check if VS Code with SN SriptSync is running

### ISSUE THREAD

**Issue by SteveMunsell** [arnoudkooi/sn-scriptsync#67]
I am unable to connect from SNUtils to VSCode using sn-scriptsync. 

When I look in the sn-scriptsync helper tab it shows that it's connected via the web socket

![image](https://user-images.githubusercontent.com/20819396/161286453-d25b57a1-d00e-438b-9696-a35e11cedd71.png)

but when I click the icon next to a script I get the error: Error, please check if VS Code with SN SriptSync is running

My local host says "Upgrade Required!" if that helps.

![image](https://user-images.githubusercontent.com/20819396/161287241-58570c9d-7cdb-458d-ab79-ea28212599a2.png)
![image](https://user-images.githubusercontent.com/20819396/161287398-b3c3e533-e97d-4bf4-b167-24389762664a.png)

**Comment by SteveMunsell** [comment]
![image](https://user-images.githubusercontent.com/20819396/161287241-58570c9d-7cdb-458d-ab79-ea28212599a2.png)

**Comment by arnoudkooi** [comment]
What is the browser you'r using?

**Comment by arnoudkooi** [comment]
Looks to be Brave. Please have a look at #50 
You probably need to "Shield down" your instance

**Comment by SteveMunsell** [comment]
> Looks to be Brave. Please have a look at #50 You probably need to "Shield down" your instance

Unbelievable! I cannot believe I didn't think to look at this as a possible cause. I just re-installed my OS and figured it was some weird firewall setting but you are 100% correct that it was the shield. Thank you!

**Comment by SteveMunsell** [comment]
> Looks to be Brave. Please have a look at #50 You probably need to "Shield down" your instance

> Looks to be Brave. Please have a look at #50 You probably need to "Shield down" your instance

Unbelievable! I cannot believe I didn't think to look at this as a possible cause. I just re-installed my OS and figured it was some weird firewall setting but you are 100% correct that it was the shield. Thank you!
