### ISSUE TITLE
ScriptSync failing 'Error While Saving File' - test_urls.txt file issue?

### ISSUE THREAD

**Issue by lewiswill** [arnoudkooi/sn-scriptsync#7]
The error message when trying to save/sync on VSC:

Error while saving file: { "errno": -4058, "syscall": "open", "code": "ENOENT", "path": "c:\\Users\\<NAME>\\Desktop\\SN Workspace/<SN INSTANCE>/sp_widget/UFI - Home Page 4/test_urls.txt" }

I have re-installed everything, Using the SN Util extenson on Firefox. Can't seem to resolve this issue.

3 of my colleagues have reported the same issue, we are (sadly) reverting back to the platform widget editor for now

**Comment by lewiswill** [comment]
source of the error seems to be the 'saveFieldsToServiceNow' function found in 'extension.ts' file

**Comment by arnoudkooi** [comment]
The way path separators are handled dont seem to be consistent \ vs / in your situation.
Can you try upgrading to version 1.1.5 of the VS Code extension? I update to use path.sep, instead of  a forward slash

**Comment by lewiswill** [comment]
Hi @arnoudkooi  I was already on 1.1.5 of the VS Code extension, I also reinstalled both the firefox & VSC extensions numerous times with PC restarts, No Luck! For whatever reason test_urls.txt is causing the script to error out the saveFieldsToServiceNow function?

**Comment by arnoudkooi** [comment]
1.1.5 is released after you created raised the issue.
Could you check if again post the current error message?

You get the error on save of the widget? 
When you save for example a script include, it does work?

**Comment by lewiswill** [comment]
@arnoudkooi I understand, I am 100% certain I am on 1.1.5 as of now. The slashes have indeed change,

Yes the error occurs when I try to save any widget changes. 

**Here is the error:**
Error while saving file: {
    "errno": -4058,
    "syscall": "open",
    "code": "ENOENT",
    "path": "c:\\Users\\<NAME>\\Desktop\\SN Workspace\\<SN INSTANCE>\\sp_widget\\UFI - Home Page 4\\test_urls.txt"
}

**Comment by arnoudkooi** [comment]
If you have time, can you jump on a call?
https://servicenow.zoom.us/j/147751654

**Comment by lewiswill** [comment]
@arnoudkooi Fantastic! I am downloading Zoom now.

**Comment by lewiswill** [comment]
Thanks @arnoudkooi for your help.

For anyone else with the same issue, I had to delete the workspace folder & redirect the path under extension settings.
