### ISSUE TITLE
[Feature Request] Flow Designer

### ISSUE THREAD

**Issue by V1tamnT** [arnoudkooi/sn-scriptsync#71]
This is a feature request, but more of a "can this be done" question.

I've said this before, but my workflow is greatly hampered when I cannot edit scripts within VS Code. Is it possible to get that functionality working in Flow Designer? 

We recently started using Integration Hub and I've been doing a ton of work in the AD Spokes as well as working on generic actions to replace subflows we currently use in Workflow.

If you can't, I get it, but you did manage to get workflow activity editing/saving in workflow activities, so I'm hopeful...

**Comment by arnoudkooi** [comment]
I think this is a copy of #43 I'll do a new research to see if it can be done

**Comment by V1tamnT** [comment]
I agree. I'll close this issue and follow #43.
