### ISSUE TITLE
[Enhancement] New table/field for scriptsync

### ISSUE THREAD

**Issue by crysallis** [arnoudkooi/sn-scriptsync#72]
Can you add script sync to the sp_css table css field?

**Comment by arnoudkooi** [comment]
It should be supported as of now...

**Comment by crysallis** [comment]
the </> option is there but not the one to open into vs code directly... I see only the option for the monaco editor in a new tab

**Comment by arnoudkooi** [comment]
Have you enabled VS Code scriptsync in the SN Utils popup settings tab? does it work for other fields?

**Comment by crysallis** [comment]
Yes, it worka everywhere else, i use it daily

**Comment by arnoudkooi** [comment]
Think its instance-specific, can you try it on another instance? Any console error?

**Comment by crysallis** [comment]
I'll withdraw the issue... I rebooted, and now it works... not sure why... I've noticed if I leave a screen open for a long time the icons next to the fields start to replicate... maybe it's related... but this is no longer an issue... just odd it wasn't on that one table lol... oh well... such as life
