### ISSUE TITLE
Doing a / sysid search triggers a Flow Action called Look up Images in a Docker Spoke

### ISSUE THREAD

**Issue by crysallis** [arnoudkooi/sn-scriptsync#74]
Perhaps this is just a consequence of doing a sys_id search... but when we run one it attempts to look in Remote Tables and this errors out on a Flow Action called Look Up Images as part of the Docker Spoke... We don't use or have it setup.  Now the result returned seems correct... and will find a valid sys_id when used... but if it's not a valid id or the id isn't found wondering it's triggering this Action.  It's causing some error monitoring systems to trigger for us.  

Not sure what logs I can provide you to help but let me know if there is anything.

Version 6.1.2.9

**Comment by arnoudkooi** [comment]
This seems to be an SN Utils issue, not scriptsync.
I would like to see this. Can we setup a call where you show this issue?

**Comment by arnoudkooi** [comment]
Please contact me directly, if you can show me steps to reproduce. As this is not sn-scriptsync closing this one.

**Comment by crysallis** [comment]
apologies... I just saw these updates
