### ISSUE TITLE
Could not connect to WebSocket.

### ISSUE THREAD

**Issue by psikos** [arnoudkooi/sn-scriptsync#76]
Tried everything, even reinstallation of VSC - still got the same issue:
![image](https://user-images.githubusercontent.com/57257361/215443504-0fee65a4-bc94-4bd1-8cff-e95411604f77.png)
Please help - it worked before the weekend :(

**Comment by arnoudkooi** [comment]
It does run. in VS Code?

![Code20230130 - 1127](https://user-images.githubusercontent.com/840781/215452124-0f54aaa9-6858-4d94-8e98-3a6ca55ae24b.png)

**Comment by psikos** [comment]
Thank you, Master

**Comment by arnoudkooi** [comment]
Is it fixed?
I recommend watching the install instructions and tutorial [in this video.](https://www.youtube.com/watch?v=ZDDminMjGTA&ab_channel=ArnoudKooi)
It will help auto start the server when selecting the configured folder.

**Comment by psikos** [comment]
Yest it its :)
