### ISSUE TITLE
Feature Request: Pull all property names from instance as autocomplete options for gs.getProperties

### ISSUE THREAD

**Issue by VanWeapon** [arnoudkooi/sn-scriptsync#77]
Typescript types allow for declaration of a set of constant strings like so:

```typescript
//in a .d.ts file
declare type Properties = "com.snc.someprop" | "glide.ui.something" | "custom.property.name_thing"; //etc etc
```

![image](https://user-images.githubusercontent.com/30616047/216866788-16a93d77-c9fa-4785-b7f9-f257a58eb435.png)

Then you can update the definition of `gs.getProperty` in the d.ts file like below

```typescript
    getProperty(key: Properties, alt: Object): string {}
```
![image](https://user-images.githubusercontent.com/30616047/216866952-5e60cecd-9768-4955-aeb7-1b9b7ddce34e.png)

Then, when you try to use gs.getProperty in a script, you actually get autocomplete showing you only valid property names. 

![image](https://user-images.githubusercontent.com/30616047/216867447-63ad0088-a64c-43e8-b623-aa6e8b81e449.png)

Since this list is large, this should probably only be pulled/refreshed on demand. Maybe once optionally during initial instance setup, then again as a separate command

For now, I can load this list manually by exporting to csv or something then loading into my own typedef file, but it would be cool if the extension could do this too. Maybe a similar thing could be done for table names so that GlideRecord can only be used on valid tables?

**Comment by VanWeapon** [comment]
here is some code i wrote to do this on-demand in node for table names, tho the concept applies broadly:

```js
var fs = require('fs');
const axios = require('axios');

async function getTableRest() {
    let url = 'https://ac3dev.service-now.com/api/now/table/sys_db_object?sysparm_fields=name';
    let auth = 'Basic ' + btoa('username' + ':' + 'password');
    axios
        .get(url, {
            headers: {
                Accept: 'application/json',
                'Content-Type': 'application/json',
                Authorization: auth,
            },
        })
        .then((res) => {
            // console.log(res.data.result);
            // console.log(res);
            let results = res.data.result;
            // console.log(results);

            fs.writeFileSync('./ts/tablenames.d.ts', `declare type InstanceTableNames = `);
            for (var x of results) {
                var table_name = x.name;
                if (!table_name) continue;
                fs.appendFile(
                    './ts/tablenames.d.ts',
                    `
    | "${table_name}"`,
                    { encoding: 'utf-8' },
                    () => {}
                );
            }
        });
}

getTableRest();

```

Resulting file: 
![image](https://user-images.githubusercontent.com/30616047/216892076-0f216143-6ba6-4a32-9341-af83c17620e7.png)


Then I just change the type signature of GlideRecord (and GlideAggregate)
![image](https://user-images.githubusercontent.com/30616047/216892176-aacbc757-5d45-42e2-9fa6-5d838cfbe4e1.png)


and now i have autocomplete for table names in GlideRecord:

![image](https://user-images.githubusercontent.com/30616047/216892239-2b29d8a0-079c-4094-889b-4c53926669bd.png)

**Comment by arnoudkooi** [comment]
Interesting didn't know this! Does this result in an error when the used value is not in the type, or preloaded? (that may be confusing for the average user)

**Comment by VanWeapon** [comment]
No errors, since these aren't TypeScript files they don't get checked unless the user runs a TSLint explicitly

**Comment by arnoudkooi** [comment]
Implemented :)
