### ISSUE TITLE
Instant Sync not working for Inbound Action Scripts

### ISSUE THREAD

**Issue by chrisbrannigan** [arnoudkooi/sn-scriptsync#8]
I have noticed an issue where saving scripts from VS code to ServiceNow for Inbound Action scripts does not update in ServiceNow Instantaneously, you need to reload the form to see the update. I have tested with other script types (e.g. client scripts, business rules) which work as expected. 

One thing to note is that the save button to push the script out to VS code appears against the template field just before the script field as well as on the script field itself.

**Comment by arnoudkooi** [comment]
I think this is dependent on the platform, not related to the extension...

**Comment by arnoudkooi** [comment]
As mentioned this is platform behaviour. let me know if you have a suggestion to change in the app.
