### ISSUE TITLE
New version can't save Header and Footers

### ISSUE THREAD

**Issue by gcacars** [arnoudkooi/sn-scriptsync#81]
Hi! In the last versions I can't save Header and Footers widget.
When I try, an error is showed in VS Code.
Can this be fixed?

**Comment by arnoudkooi** [comment]
Are you using the test version?

**Comment by arnoudkooi** [comment]
If this is about the new version, that is a technical preview.
If it is about the current version, please be more specific and detailed so I'm able to troubleshoot
