### ISSUE TITLE
SP_NG_Template - ACL Error

### ISSUE THREAD

**Issue by NeuraalLabs** [arnoudkooi/sn-scriptsync#82]
When you sync a widget with NG-Templates, upon saving a ng-template from the sp_ng_template sub-folder you get an ACL error. If you sync the NG-Template individually it saves correctly. Widget and Templates are in the same scope.

VSCode Version: 2.7.3
SN Utils (On Prim): 7.0.8.0

**Comment by arnoudkooi** [comment]
Do you experience the issue when you switch the instance to the scope of the Widget?

**Comment by arnoudkooi** [comment]
To be sure is the application picker in your Instance pointing to the matching scope?
My guess is the scope sys_id is not being added to the request for this edge case.

I'm working on a big change where this will also work differently.
Please use the workaround so long, as I won't update the current 2.x version
if you still experience issues after the 3.0 update, let me know
