### ISSUE TITLE
<script> tag corrupted (escaped) in UI Macros

### ISSUE THREAD

**Issue by SongPing** [arnoudkooi/sn-scriptsync#83]
When editing components (jelly xml code in UI Macros e.g.) in Visual Studio, every time on saving the "script" tags get corrupted (escaped). From "<script>" to "&lt;script&gt;"  and from "</script>" to  "&lt;/script&gt;"
All other tags seems to be handled correctly.

As a feature request:
To improve the extension even further, there could be an automatically handling of special characters like <,>,& in javascript code:
Add `<j2:set var="jvar_amp" value="&amp;"/>` to the xml-file and replace `&` in code by `$[jvar_amp]`
For <,>, ... accordingly.
Thanks!!!

**Comment by arnoudkooi** [comment]
I think this is this solved by the below solution from the FAQ in the readme:

> FAQs
> I'm using <script> tags in a widget HTML template, and they do not sync to my instance properly. How can I resolve this?
> 
> Solution (See https://github.com/arnoudkooi/sn-scriptsync/issues/24): In your ServiceNow instance, set the following system property:
> 
> glide.rest.sanitize_request_input = false
> I get an error when using in Safari: "User Not Authenticated"

Can you try and let me know?

**Comment by arnoudkooi** [comment]
No worries, glad it worked. I'll expand / clarify the faq text a bit!
