### ISSUE TITLE
SN Util is not sending the changes from VSCode to instance

### ISSUE THREAD

**Issue by RahmanM** [arnoudkooi/sn-scriptsync#84]
Hi there,

Somehow SN Util stopped working for me which it was working fine until this morning. SN Util connects to VS code, when I click the widget it sends the widget data to the VS Code however when I do the changes and save the record e.g. client_script.js the updates are not sent to instance. What I have done:

1. Closed the chrome and reopened and relogged in to the instance 
2. /token to re-send the token
3. Closed VS Code and re-opened and strarted the SnScriptSync 
4. Uninstalled the SnScriptSync in VSCode and re-installed
5. Opened a new VS Code folder and got the files from the instance 
6. Connected to instance from Microsoft Edge

It seems like I am in version 3.0. None of them resolved the issue. Is this a known issue or is there anything else I need to do?

Many thanks

**Comment by RahmanM** [comment]
Hi Arnoud, happy to get in a call. I sent you my mobile number but a zoom or teams call will be better I guess.

**Comment by arnoudkooi** [comment]
I just published a fix, version 3.0.1
Can you upgrade and try again? You must resync the widget from the instance save button.

**Comment by RahmanM** [comment]
That did the trick. Thank you so much! I reinstalled both Chrome and VSCode and re-synced the widget and it is work.

Appreciate your quick response and solution!

**Comment by arnoudkooi** [comment]
Great, happy it is solved. Thanks for raising the issue.
