### ISSUE TITLE
Naming of files is suboptimal for some tables

### ISSUE THREAD

**Issue by Blenderpics** [arnoudkooi/sn-scriptsync#86]
For some tables the default naming causes a lot of file name conflicts.  
For example: syncing ACLs will create a file with a filename pattern of [tablename].script.js.  
Since you will have more than one ACL for each table most of the time, this will create a lot of weirdly named files, since they will always conflict, due to the otherwise equal file name.  
  
It would be nice if the the table name and/or (in case of ACLs for example) the action (read/write/etc) would be appended to the file.

**Comment by arnoudkooi** [comment]
Looks like this one can be managed via #85
