### ISSUE TITLE
Inconsistent naming when using the studio sync

### ISSUE THREAD

**Issue by Blenderpics** [arnoudkooi/sn-scriptsync#87]
The naming of the generated files within VS Code seem to depend on wether or not you have synced the file with the studio sync function, or with the button on the field.  
An example:  
A `calculation` script within a `sys_dictionary` row where the `name` is `display_value` and the `display` is `Display Value` will get named  
 - DisplayValue.calculation.js when synced with the studio sync  
 - Display-Value.calculation.js when synced with the sync button on the field itself.

**Comment by Blenderpics** [comment]
The given example is a bit confusing.  
I have a column with `display_value` as it's name and `Display Value` as it's display value.  
Just to clearify thingss

**Comment by arnoudkooi** [comment]
On SN Utils side I removed a regex that changed the name. Once you upgrade to 7.1.1.3 this should be fixed.

Note:
 The Icon button uses g_form.getDisplayValue() to retrieve the name where the Load scope.
The Load Scope uses the sys_scope field from sys_metadata. I think this should be the same
