### ISSUE TITLE
"Load/Refresh Artifacts From Scope" can load subset (or none) of scope if > 10000 sys_metadata records

### ISSUE THREAD

**Issue by mevops** [arnoudkooi/sn-scriptsync#96]
I believe that this will be a universal problem rather than just me.

### My understanding of the problem:

- The default limit for the Table API when sysparm_limit is not set is 10000 records
- When getting sys_metadata records for the scope, sysparm_limit is not set and therefore defaults to 10000 when the browser plugin makes the request: function [requestScopeArtifacts](https://github.com/arnoudkooi/sn-scriptsync/blob/dba5ed97e78befa684ea9293d6db63c2fb5f56a1/src/extension.ts#L552)
- The SN-Utils app doesn't page in its method [requestRecords](https://github.com/arnoudkooi/ServiceNow-Utils/blob/2d49f458d812163694fc68f9c1724301b9e94f26/scriptsync.js#L362)
- Therefore only 10000 sys_metadata records are returned to the VS Code plugin
- This is the subset that the scope tree is then generated from

### How it manifests:
There seem to be two options:

1. The scope tree is built but only with a subset of the records
2. The job silently fails and never completes. My guess is it's based on the content of the subset received and whether they include anything it can generate from. For my app this is happening with the default 10000 limit

### How to replicate it:

I can fairly easily trigger various levels of the issue/fix the issue by setting sysparm_limit=X within the file ~/.vscode/extensions/arnoudkooicom.sn-scriptsync-3.3.3out/extension.js then restarting the VS Code extensions host

Here shows that it silently fails when loading too few sys_metadata records:

![image](https://github.com/arnoudkooi/sn-scriptsync/assets/67866833/35b21457-e6a5-4ad1-ae6a-35b706aba878)

Here shows a subset load that did successfully load a subset of the tree and notify VS Code it was complete (sysparm_limit set to 20000):

![image](https://github.com/arnoudkooi/sn-scriptsync/assets/67866833/6c2f6715-5f80-4cde-a743-1f3182380545)

Here shows a full successful load (sysparm_limit set to 100000):

![image](https://github.com/arnoudkooi/sn-scriptsync/assets/67866833/5103e407-00ef-4c58-93d1-7aa362b9b05f)

### How I think it could be fixed

Obviously setting a massive sysparm_limit would solve the problem, however I think the best way would actually be to make a change to the SN-Utils browser app so that the requestRecords method pages if it receives 10000 results (or you could use the X-Total-Count header to track it)

**Comment by arnoudkooi** [comment]
Are you still experiencing this issue? 
I deliberately set a limit, so when you're in Global, don't try to pull in everything.
